apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-signing-operator
  namespace: registry-system
  labels:
    control-plane: image-signing-operator
spec:
  selector:
    matchLabels:
      control-plane: image-signing-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: image-signing-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: tmaxcloudck/image-signing-operator:0.0.1
        name: manager
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: "image-signing-operator"
          - name: TZ
            value: Asia/Seoul
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
