# permissions for end users to edit imagesigns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagesign-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagesigns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagesigns/status
  verbs:
  - get
