# permissions for end users to edit imagesigners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagesigner-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagesigners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagesigners/status
  verbs:
  - get
