# permissions for end users to view imagesignrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagesignrequest-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagesignrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagesignrequests/status
  verbs:
  - get
