# permissions for end users to edit imagesignrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagesignrequest-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagesignrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagesignrequests/status
  verbs:
  - get
