# permissions for end users to view imagesigners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagesigner-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagesigners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagesigners/status
  verbs:
  - get
