# permissions for end users to edit signerkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: signerkey-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - signerkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - signerkeys/status
  verbs:
  - get
